import DashboardNav from "@/components/DashboardNav";
import "@/app/globals.css";
import { Inter } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
export const metadata = {
  title: "Dashboard",
  description: "Generated by Next.js",
};
const inter = Inter({ subsets: ["latin"] });
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <NextTopLoader showSpinner={false} color="#708090" />
        <DashboardNav />
        {children}
      </body>
    </html>
  );
}
